assetic:
    bundles: [ AnimeDbShikimoriRelatedItemsWidgetBundle ]
    assets:
        stylesheets:
            inputs:
                - @AnimeDbShikimoriRelatedItemsWidgetBundle/Resources/public/css/*.css